Only_test/Models/ErrorViewModel.cs
namespace Only_test.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Only_test/Models/Only_tContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Only_test.Models
{
    public partial class Only_tContext : DbContext
    {
        public Only_tContext()
        {
        }

        public Only_tContext(DbContextOptions<Only_tContext> options)
            : base(options)
        {
        }

        public virtual DbSet<User> Users { get; set; } = null!;

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseNpgsql("Host=localhost;Port=5432;Database=Only_t;Username=postgres;Password=25riboza25");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>(entity =>
            {
                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .UseIdentityAlwaysColumn();

                entity.Property(e => e.Department).HasColumnType("character varying");

                entity.Property(e => e.FullName).HasMaxLength(150);

                entity.Property(e => e.ParentDepartment)
                    .HasColumnType("character varying")
                    .HasColumnName("Parent_department");

                entity.Property(e => e.Position).HasColumnType("character varying");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

Only_test/Models/User.cs
using System;
using System.Collections.Generic;

namespace Only_test.Models
{
    public partial class User
    {
        public int Id { get; set; }
        public string FullName { get; set; } = null!;
        public string Position { get; set; } = null!;
        public string Department { get; set; } = null!;
        public string? ParentDepartment { get; set; }
    }
}

Only_test/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Only_test.Models;
using System.Diagnostics;

namespace Only_test.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        Only_tContext db;
        public HomeController(Only_tContext context)
        {
            db = context;
        }

        //public HomeController(ILogger<HomeController> logger)
        //{
        //    _logger = logger;
        //}

        public async Task <IActionResult> Index()
        {
            return View(await db.Users.ToListAsync());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Only_test/Controllers/ImportUsersController.cs
using Microsoft.AspNetCore.Mvc;
using ClosedXML.Excel;
using Only_test.Models;

namespace Only_test.Controllers
{
    public class ImportUsersController : Controller
    {
        IWebHostEnvironment _appEnviroment;
        Only_tContext db;
        List<User> usersList = new List<User>();
        string path;
        public ImportUsersController(Only_tContext context, IWebHostEnvironment appEnviroment)
        {
            _appEnviroment = appEnviroment;
            db = context;
        }
        public IActionResult Import()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddFile(IFormFile uploadedFile)
        {
            if (ModelState.IsValid)
            {
                if (uploadedFile != null)
                {
                    path = "/ExcelFiles/" + uploadedFile.FileName;
                    using (var fileStream = new FileStream(_appEnviroment.WebRootPath + path, FileMode.Create))
                    {
                        await uploadedFile.CopyToAsync(fileStream);
                    }
                }

                using (var wb = new XLWorkbook(_appEnviroment.WebRootPath + path))
                {
                    var ws = wb.Worksheet(1);

                        
                        foreach (var row in ws.RowsUsed().Skip(1))
                        {

                            try
                            {
                                User user = new User
                                {
                                    FullName = row.Cell(4).Value.ToString(),
                                    Department = row.Cell(1).Value.ToString(),
                                    ParentDepartment = row.Cell(2).Value.ToString(),
                                    Position = row.Cell(3).Value.ToString()
                                };
                                usersList.Add(user);
                                
                            }
                            catch (Exception ex)
                            {
                                
                            }
                        }
                    db.Users.AddRangeAsync(usersList);
                    await db.SaveChangesAsync();
                }
            }
            
            return RedirectToAction("Index","Home");
        }
    }
}

Only_test/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model IEnumerable<Only_test.Models.User>

<div class="text-center">
    <h2 class="display-4">Список полльзователей</h2>
    <form method="get">
        <div>
            <p>Выбирите отдел</p>
            <select asp-items=""></select>
            <input type="submit" value="отфилтровать"/>
         </div>
    </form>

   <table>
       <tr><th>ФИО</th> <th>Должность </th> <th>Отдел</th> <th>Родительский отдел</th> </tr>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.FullName</td>
                <td>@item.Position</td>
                <td>@item.Department</td>
                <td>@item.ParentDepartment</td>
            </tr>
        }
    </table>
</div>

Only_test/Views/ImportUsers/Import.cshtml
@model IEnumerable<Only_test.Models.User>

@{
    ViewData["Title"] = "Import";
}

<h1>Index import</h1>
<form asp-action="AddFile" asp-controller="ImportUsers" method="post" enctype="multipart/form-data">
    <div>
        <h3>Загрузите фаил</h3>
        <input type="file" name="uploadedFile"/>
        <input type="submit"  value="Загрузить"/>
    </div>
</form>
    

Only_test/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Only_test</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Only_test.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Only_test</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Only_test
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>